apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: kidecar-game
  namespace: default
spec:
  replicas: 2
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  gameServerTemplate:
    spec:
      containers:
      - name: kidecar-game
        image: 113745426946.dkr.ecr.us-east-1.amazonaws.com/xuetaotest/kidecar-game:v3.3
        ports:
        - containerPort: 14005
        - containerPort: 14004